export interface CountryCode {
  name: string;
  dialCode: string;
  isoCode: string;
}

/** ITU-T E.164 dial codes for all UN-recognised countries + common territories. */
export const COUNTRY_CODES: CountryCode[] = [
  { name: 'Afghanistan', dialCode: '+93', isoCode: 'AF' },
  { name: 'Albania', dialCode: '+355', isoCode: 'AL' },
  { name: 'Algeria', dialCode: '+213', isoCode: 'DZ' },
  { name: 'Andorra', dialCode: '+376', isoCode: 'AD' },
  { name: 'Angola', dialCode: '+244', isoCode: 'AO' },
  { name: 'Argentina', dialCode: '+54', isoCode: 'AR' },
  { name: 'Armenia', dialCode: '+374', isoCode: 'AM' },
  { name: 'Australia', dialCode: '+61', isoCode: 'AU' },
  { name: 'Austria', dialCode: '+43', isoCode: 'AT' },
  { name: 'Azerbaijan', dialCode: '+994', isoCode: 'AZ' },
  { name: 'Bahrain', dialCode: '+973', isoCode: 'BH' },
  { name: 'Bangladesh', dialCode: '+880', isoCode: 'BD' },
  { name: 'Belarus', dialCode: '+375', isoCode: 'BY' },
  { name: 'Belgium', dialCode: '+32', isoCode: 'BE' },
  { name: 'Belize', dialCode: '+501', isoCode: 'BZ' },
  { name: 'Benin', dialCode: '+229', isoCode: 'BJ' },
  { name: 'Bhutan', dialCode: '+975', isoCode: 'BT' },
  { name: 'Bolivia', dialCode: '+591', isoCode: 'BO' },
  { name: 'Bosnia & Herzegovina', dialCode: '+387', isoCode: 'BA' },
  { name: 'Botswana', dialCode: '+267', isoCode: 'BW' },
  { name: 'Brazil', dialCode: '+55', isoCode: 'BR' },
  { name: 'Brunei', dialCode: '+673', isoCode: 'BN' },
  { name: 'Bulgaria', dialCode: '+359', isoCode: 'BG' },
  { name: 'Burkina Faso', dialCode: '+226', isoCode: 'BF' },
  { name: 'Burundi', dialCode: '+257', isoCode: 'BI' },
  { name: 'Cambodia', dialCode: '+855', isoCode: 'KH' },
  { name: 'Cameroon', dialCode: '+237', isoCode: 'CM' },
  { name: 'Canada', dialCode: '+1', isoCode: 'CA' },
  { name: 'Cape Verde', dialCode: '+238', isoCode: 'CV' },
  { name: 'Central African Republic', dialCode: '+236', isoCode: 'CF' },
  { name: 'Chad', dialCode: '+235', isoCode: 'TD' },
  { name: 'Chile', dialCode: '+56', isoCode: 'CL' },
  { name: 'China', dialCode: '+86', isoCode: 'CN' },
  { name: 'Colombia', dialCode: '+57', isoCode: 'CO' },
  { name: 'Comoros', dialCode: '+269', isoCode: 'KM' },
  { name: 'Congo (DRC)', dialCode: '+243', isoCode: 'CD' },
  { name: 'Congo (Republic)', dialCode: '+242', isoCode: 'CG' },
  { name: 'Costa Rica', dialCode: '+506', isoCode: 'CR' },
  { name: 'Croatia', dialCode: '+385', isoCode: 'HR' },
  { name: 'Cuba', dialCode: '+53', isoCode: 'CU' },
  { name: 'Cyprus', dialCode: '+357', isoCode: 'CY' },
  { name: 'Czech Republic', dialCode: '+420', isoCode: 'CZ' },
  { name: 'Denmark', dialCode: '+45', isoCode: 'DK' },
  { name: 'Djibouti', dialCode: '+253', isoCode: 'DJ' },
  { name: 'Dominican Republic', dialCode: '+1809', isoCode: 'DO' },
  { name: 'Ecuador', dialCode: '+593', isoCode: 'EC' },
  { name: 'Egypt', dialCode: '+20', isoCode: 'EG' },
  { name: 'El Salvador', dialCode: '+503', isoCode: 'SV' },
  { name: 'Equatorial Guinea', dialCode: '+240', isoCode: 'GQ' },
  { name: 'Eritrea', dialCode: '+291', isoCode: 'ER' },
  { name: 'Estonia', dialCode: '+372', isoCode: 'EE' },
  { name: 'Eswatini', dialCode: '+268', isoCode: 'SZ' },
  { name: 'Ethiopia', dialCode: '+251', isoCode: 'ET' },
  { name: 'Fiji', dialCode: '+679', isoCode: 'FJ' },
  { name: 'Finland', dialCode: '+358', isoCode: 'FI' },
  { name: 'France', dialCode: '+33', isoCode: 'FR' },
  { name: 'Gabon', dialCode: '+241', isoCode: 'GA' },
  { name: 'Gambia', dialCode: '+220', isoCode: 'GM' },
  { name: 'Georgia', dialCode: '+995', isoCode: 'GE' },
  { name: 'Germany', dialCode: '+49', isoCode: 'DE' },
  { name: 'Ghana', dialCode: '+233', isoCode: 'GH' },
  { name: 'Greece', dialCode: '+30', isoCode: 'GR' },
  { name: 'Guatemala', dialCode: '+502', isoCode: 'GT' },
  { name: 'Guinea', dialCode: '+224', isoCode: 'GN' },
  { name: 'Guinea-Bissau', dialCode: '+245', isoCode: 'GW' },
  { name: 'Guyana', dialCode: '+592', isoCode: 'GY' },
  { name: 'Haiti', dialCode: '+509', isoCode: 'HT' },
  { name: 'Honduras', dialCode: '+504', isoCode: 'HN' },
  { name: 'Hong Kong', dialCode: '+852', isoCode: 'HK' },
  { name: 'Hungary', dialCode: '+36', isoCode: 'HU' },
  { name: 'Iceland', dialCode: '+354', isoCode: 'IS' },
  { name: 'India', dialCode: '+91', isoCode: 'IN' },
  { name: 'Indonesia', dialCode: '+62', isoCode: 'ID' },
  { name: 'Iran', dialCode: '+98', isoCode: 'IR' },
  { name: 'Iraq', dialCode: '+964', isoCode: 'IQ' },
  { name: 'Ireland', dialCode: '+353', isoCode: 'IE' },
  { name: 'Israel', dialCode: '+972', isoCode: 'IL' },
  { name: 'Italy', dialCode: '+39', isoCode: 'IT' },
  { name: 'Ivory Coast', dialCode: '+225', isoCode: 'CI' },
  { name: 'Jamaica', dialCode: '+1876', isoCode: 'JM' },
  { name: 'Japan', dialCode: '+81', isoCode: 'JP' },
  { name: 'Jordan', dialCode: '+962', isoCode: 'JO' },
  { name: 'Kazakhstan', dialCode: '+7', isoCode: 'KZ' },
  { name: 'Kenya', dialCode: '+254', isoCode: 'KE' },
  { name: 'Kuwait', dialCode: '+965', isoCode: 'KW' },
  { name: 'Kyrgyzstan', dialCode: '+996', isoCode: 'KG' },
  { name: 'Laos', dialCode: '+856', isoCode: 'LA' },
  { name: 'Latvia', dialCode: '+371', isoCode: 'LV' },
  { name: 'Lebanon', dialCode: '+961', isoCode: 'LB' },
  { name: 'Lesotho', dialCode: '+266', isoCode: 'LS' },
  { name: 'Liberia', dialCode: '+231', isoCode: 'LR' },
  { name: 'Libya', dialCode: '+218', isoCode: 'LY' },
  { name: 'Liechtenstein', dialCode: '+423', isoCode: 'LI' },
  { name: 'Lithuania', dialCode: '+370', isoCode: 'LT' },
  { name: 'Luxembourg', dialCode: '+352', isoCode: 'LU' },
  { name: 'Macau', dialCode: '+853', isoCode: 'MO' },
  { name: 'Madagascar', dialCode: '+261', isoCode: 'MG' },
  { name: 'Malawi', dialCode: '+265', isoCode: 'MW' },
  { name: 'Malaysia', dialCode: '+60', isoCode: 'MY' },
  { name: 'Maldives', dialCode: '+960', isoCode: 'MV' },
  { name: 'Mali', dialCode: '+223', isoCode: 'ML' },
  { name: 'Malta', dialCode: '+356', isoCode: 'MT' },
  { name: 'Mauritania', dialCode: '+222', isoCode: 'MR' },
  { name: 'Mauritius', dialCode: '+230', isoCode: 'MU' },
  { name: 'Mexico', dialCode: '+52', isoCode: 'MX' },
  { name: 'Moldova', dialCode: '+373', isoCode: 'MD' },
  { name: 'Monaco', dialCode: '+377', isoCode: 'MC' },
  { name: 'Mongolia', dialCode: '+976', isoCode: 'MN' },
  { name: 'Montenegro', dialCode: '+382', isoCode: 'ME' },
  { name: 'Morocco', dialCode: '+212', isoCode: 'MA' },
  { name: 'Mozambique', dialCode: '+258', isoCode: 'MZ' },
  { name: 'Myanmar', dialCode: '+95', isoCode: 'MM' },
  { name: 'Namibia', dialCode: '+264', isoCode: 'NA' },
  { name: 'Nepal', dialCode: '+977', isoCode: 'NP' },
  { name: 'Netherlands', dialCode: '+31', isoCode: 'NL' },
  { name: 'New Zealand', dialCode: '+64', isoCode: 'NZ' },
  { name: 'Nicaragua', dialCode: '+505', isoCode: 'NI' },
  { name: 'Niger', dialCode: '+227', isoCode: 'NE' },
  { name: 'Nigeria', dialCode: '+234', isoCode: 'NG' },
  { name: 'North Korea', dialCode: '+850', isoCode: 'KP' },
  { name: 'North Macedonia', dialCode: '+389', isoCode: 'MK' },
  { name: 'Norway', dialCode: '+47', isoCode: 'NO' },
  { name: 'Oman', dialCode: '+968', isoCode: 'OM' },
  { name: 'Pakistan', dialCode: '+92', isoCode: 'PK' },
  { name: 'Palestine', dialCode: '+970', isoCode: 'PS' },
  { name: 'Panama', dialCode: '+507', isoCode: 'PA' },
  { name: 'Papua New Guinea', dialCode: '+675', isoCode: 'PG' },
  { name: 'Paraguay', dialCode: '+595', isoCode: 'PY' },
  { name: 'Peru', dialCode: '+51', isoCode: 'PE' },
  { name: 'Philippines', dialCode: '+63', isoCode: 'PH' },
  { name: 'Poland', dialCode: '+48', isoCode: 'PL' },
  { name: 'Portugal', dialCode: '+351', isoCode: 'PT' },
  { name: 'Qatar', dialCode: '+974', isoCode: 'QA' },
  { name: 'Romania', dialCode: '+40', isoCode: 'RO' },
  { name: 'Russia', dialCode: '+7', isoCode: 'RU' },
  { name: 'Rwanda', dialCode: '+250', isoCode: 'RW' },
  { name: 'Saudi Arabia', dialCode: '+966', isoCode: 'SA' },
  { name: 'Senegal', dialCode: '+221', isoCode: 'SN' },
  { name: 'Serbia', dialCode: '+381', isoCode: 'RS' },
  { name: 'Sierra Leone', dialCode: '+232', isoCode: 'SL' },
  { name: 'Singapore', dialCode: '+65', isoCode: 'SG' },
  { name: 'Slovakia', dialCode: '+421', isoCode: 'SK' },
  { name: 'Slovenia', dialCode: '+386', isoCode: 'SI' },
  { name: 'Somalia', dialCode: '+252', isoCode: 'SO' },
  { name: 'South Africa', dialCode: '+27', isoCode: 'ZA' },
  { name: 'South Korea', dialCode: '+82', isoCode: 'KR' },
  { name: 'South Sudan', dialCode: '+211', isoCode: 'SS' },
  { name: 'Spain', dialCode: '+34', isoCode: 'ES' },
  { name: 'Sri Lanka', dialCode: '+94', isoCode: 'LK' },
  { name: 'Sudan', dialCode: '+249', isoCode: 'SD' },
  { name: 'Suriname', dialCode: '+597', isoCode: 'SR' },
  { name: 'Sweden', dialCode: '+46', isoCode: 'SE' },
  { name: 'Switzerland', dialCode: '+41', isoCode: 'CH' },
  { name: 'Syria', dialCode: '+963', isoCode: 'SY' },
  { name: 'Taiwan', dialCode: '+886', isoCode: 'TW' },
  { name: 'Tajikistan', dialCode: '+992', isoCode: 'TJ' },
  { name: 'Tanzania', dialCode: '+255', isoCode: 'TZ' },
  { name: 'Thailand', dialCode: '+66', isoCode: 'TH' },
  { name: 'Timor-Leste', dialCode: '+670', isoCode: 'TL' },
  { name: 'Togo', dialCode: '+228', isoCode: 'TG' },
  { name: 'Trinidad & Tobago', dialCode: '+1868', isoCode: 'TT' },
  { name: 'Tunisia', dialCode: '+216', isoCode: 'TN' },
  { name: 'Turkey', dialCode: '+90', isoCode: 'TR' },
  { name: 'Turkmenistan', dialCode: '+993', isoCode: 'TM' },
  { name: 'Uganda', dialCode: '+256', isoCode: 'UG' },
  { name: 'Ukraine', dialCode: '+380', isoCode: 'UA' },
  { name: 'United Arab Emirates', dialCode: '+971', isoCode: 'AE' },
  { name: 'United Kingdom', dialCode: '+44', isoCode: 'GB' },
  { name: 'United States', dialCode: '+1', isoCode: 'US' },
  { name: 'Uruguay', dialCode: '+598', isoCode: 'UY' },
  { name: 'Uzbekistan', dialCode: '+998', isoCode: 'UZ' },
  { name: 'Venezuela', dialCode: '+58', isoCode: 'VE' },
  { name: 'Vietnam', dialCode: '+84', isoCode: 'VN' },
  { name: 'Yemen', dialCode: '+967', isoCode: 'YE' },
  { name: 'Zambia', dialCode: '+260', isoCode: 'ZM' },
  { name: 'Zimbabwe', dialCode: '+263', isoCode: 'ZW' },
].sort((a, b) => a.name.localeCompare(b.name));

export const DEFAULT_COUNTRY: CountryCode = COUNTRY_CODES.find((c) => c.isoCode === 'IN')!;
