export const typography = {
  fontFamily: {
    regular: 'Nunito_400Regular',
    semiBold: 'Nunito_600SemiBold',
    bold: 'Nunito_700Bold',
    extraBold: 'Nunito_800ExtraBold',
    black: 'Nunito_900Black',
  },

  fontSize: {
    xs: 11,
    sm: 12,
    md: 13,
    base: 14.5,
    lg: 16,
    xl: 18,
    '2xl': 20,
    '3xl': 22,
    '4xl': 26,
    '5xl': 34,
  },

  lineHeight: {
    xs: 15,
    sm: 17,
    md: 18,
    base: 21,
    lg: 23,
    xl: 26,
    '2xl': 28,
    '3xl': 30,
    '4xl': 34,
    '5xl': 42,
  },

  fontWeight: {
    regular: '400' as const,
    semiBold: '600' as const,
    bold: '700' as const,
    extraBold: '800' as const,
    black: '900' as const,
  },

  letterSpacing: {
    tighter: -0.5,
    tight: -0.3,
    normal: 0,
    wide: 0.3,
    wider: 0.6,
    widest: 0.8,
  },
} as const;

export const textPresets = {
  displayLarge: {
    fontFamily: 'Nunito_900Black',
    fontSize: 34,
    lineHeight: 42,
    fontWeight: '900' as const,
    letterSpacing: -0.8,
  },
  displaySmall: {
    fontFamily: 'Nunito_900Black',
    fontSize: 26,
    lineHeight: 34,
    fontWeight: '900' as const,
    letterSpacing: -0.5,
  },
  headingLarge: {
    fontFamily: 'Nunito_800ExtraBold',
    fontSize: 22,
    lineHeight: 30,
    fontWeight: '800' as const,
    letterSpacing: -0.3,
  },
  headingMedium: {
    fontFamily: 'Nunito_800ExtraBold',
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '800' as const,
    letterSpacing: -0.2,
  },
  headingSmall: {
    fontFamily: 'Nunito_800ExtraBold',
    fontSize: 17,
    lineHeight: 24,
    fontWeight: '800' as const,
  },
  bodyLarge: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 16,
    lineHeight: 23,
    fontWeight: '600' as const,
  },
  bodyMedium: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 14.5,
    lineHeight: 21,
    fontWeight: '600' as const,
  },
  bodySmall: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600' as const,
  },
  labelLarge: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '700' as const,
  },
  labelMedium: {
    fontFamily: 'Nunito_700Bold',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700' as const,
  },
  labelSmall: {
    fontFamily: 'Nunito_800ExtraBold',
    fontSize: 11.5,
    lineHeight: 16,
    fontWeight: '800' as const,
    letterSpacing: 0.6,
    textTransform: 'uppercase' as const,
  },
  caption: {
    fontFamily: 'Nunito_600SemiBold',
    fontSize: 11.5,
    lineHeight: 16,
    fontWeight: '600' as const,
  },
  overline: {
    fontFamily: 'Nunito_800ExtraBold',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '800' as const,
    letterSpacing: 0.8,
    textTransform: 'uppercase' as const,
  },
} as const;
